name: Build Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Python sürümünüzü belirtin

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile main.py  # Burada main.py'yi kendi ana dosyanızla değiştirin

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: dist/main.exe  # Burada main.exe'yi kendi exe dosyanızın adıyla değiştirin
